# Generated by Django 2.1.3 on 2018-12-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workout_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=1)),
                ('workout', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Workout')),
            ],
        ),
    ]
