# Generated by Django 2.1.3 on 2018-12-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workoutevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='weekday',
        ),
    ]
