# Generated by Django 2.1.3 on 2018-12-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_workout_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedset',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='api.Exercise'),
        ),
        migrations.AlterField(
            model_name='completedworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_workouts', to='api.Workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.Workout'),
        ),
        migrations.AlterField(
            model_name='workoutevent',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='api.Workout'),
        ),
    ]
