# Generated by Django 2.1.3 on 2018-12-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181224_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='api.Workout')),
            ],
        ),
        migrations.RemoveField(
            model_name='completedworkout',
            name='workout',
        ),
        migrations.DeleteModel(
            name='CompletedWorkout',
        ),
        migrations.AddField(
            model_name='completedset',
            name='workout_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='api.WorkoutSession'),
        ),
    ]
