# Generated by Django 2.1.3 on 2018-12-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181228_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='api.Exercise')),
                ('workout_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.WorkoutSession')),
            ],
        ),
        migrations.RenameField(
            model_name='completedset',
            old_name='reps_completed',
            new_name='reps',
        ),
        migrations.RemoveField(
            model_name='completedset',
            name='workout_session',
        ),
        migrations.AlterField(
            model_name='completedset',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.CompletedExercise'),
        ),
    ]
